### ISSUE TITLE
The app seems to do nothing

### ISSUE THREAD

**Issue by aggalex** [kjlaw89/archetype#7]
After I finish the wizard and have filled all the required info, I press "Generate project" and nothing happens. I tried runing archetype from the terminal to see the output, but I couldn't find anything to fix it.
this is the output:

```
(com.github.kjlaw89.archetype:9542): Gtk-CRITICAL **: gtk_file_filter_get_name: assertion 'GTK_IS_FILE_FILTER (filter)' failed
Initialized empty Git repository in /tmp/com.github.aggalex.myapp/.git/
[master (root-commit) facb38e] Initial commit for My app
 47 files changed, 5201 insertions(+)
 create mode 100644 .editorconfig
 create mode 100644 .gitignore
 create mode 100644 .travis.yml
 create mode 100644 AUTHORS.md
 create mode 100644 LICENSE.md
 create mode 100644 README.md
 create mode 100755 app
 create mode 100644 com.github.aggalex.myapp.json
 create mode 100644 data/com.github.aggalex.myapp.appdata.xml
 create mode 100644 data/com.github.aggalex.myapp.desktop
 create mode 100644 data/com.github.aggalex.myapp.gresource.xml
 create mode 100644 data/com.github.aggalex.myapp.gschema.xml
 create mode 100644 data/css/style.css
 create mode 100644 data/images/com.github.aggalex.myapp.png
 create mode 100644 data/images/com.github.aggalex.myapp.svg
 create mode 100644 data/images/icons/128/com.github.aggalex.myapp.svg
 create mode 100644 data/images/icons/16/com.github.aggalex.myapp.svg
 create mode 100644 data/images/icons/24/com.github.aggalex.myapp.svg
 create mode 100644 data/images/icons/32/com.github.aggalex.myapp.svg
 create mode 100644 data/images/icons/48/com.github.aggalex.myapp.svg
 create mode 100644 data/images/icons/64/com.github.aggalex.myapp.svg
 create mode 100644 data/images/screenshot.png
 create mode 100644 data/meson.build
 create mode 100644 debian/changelog
 create mode 100644 debian/compat
 create mode 100644 debian/control
 create mode 100644 debian/copyright
 create mode 100755 debian/rules
 create mode 100644 debian/source/formart
 create mode 100644 meson.build
 create mode 100644 meson/post_install.py
 create mode 100644 po/LINGUAS
 create mode 100644 po/POTFILES
 create mode 100644 po/com.github.aggalex.myapp.pot
 create mode 100644 po/meson.build
 create mode 100644 src/Application.vala
 create mode 100644 src/Main.vala
 create mode 100644 src/Window.vala
 create mode 100644 src/configs/Constants.vala
 create mode 100644 src/configs/Settings.vala
 create mode 100644 src/controllers/AppController.vala
 create mode 100644 src/meson.build
 create mode 100644 src/views/AppView.vala
 create mode 100644 src/widgets/HeaderBar.vala
 create mode 100644 tests/assert.vala
 create mode 100644 tests/meson.build
 create mode 100644 tests/test.vala

** (com.github.kjlaw89.archetype:9542): WARNING **: Template.vala:287: Unable to move temp directory to /home/alex/Programs/Vala/test/com.github.aggalex.myapp - Can't recursively copy directory
```

Seems like it wants to copy a directory from a temporary place to my designated folder that I chose, but it can't due to it's inability to copy recursively. If you use the ```cp``` command, be sure to add the ```-r``` option.

**Comment by pavlepiramida** [comment]
I can confirm the same issue

**Comment by kjlaw89** [comment]
@aggalex  Interesting... I'm actually just using GLib.File to change the folder's path. I may try to do a `mv` command to see if that works better.

Can you try to move the folder manually from /tmp and see if it lets you or gives you an error? In your log it was `/tmp/com.github.aggalex.myapp`.

**Comment by pavlepiramida** [comment]
@kjlaw89 

Made work directory in /tmp,and Archetype worked as expected.
Project is created and moved,but its tied to /tmp.

**Comment by kjlaw89** [comment]
@pavlepiramida 

When you say that it's tied to /tmp, what message or error are you getting when you try to move it elsewhere? As long as you remove the build directory and rebuild (which may not be necessary) it should rebuild fine. That said, I know for the Gnome Builder file that I specify the export path there and you might have to adjust that file if you move it. I'm not 100% certain on how that file works I just know it has a project path specified so I figured I'd replace it in case it was needed...

Edit: I'm also working on an update that attempts to use the `mv` command instead of Glib to change the directory as well. Hopefully I'll have that finished tonight and out by tomorrow. Not 100% sure on if that'll help in your case though.

**Comment by pavlepiramida** [comment]
I suck at explaining stuff :smile: 
Creating work directory in /tmp and setting project path to it,allows Archetype to do its magic.
It creates project specified by me,without any errors.
Moving work directory out of /tmp to any other location does not break anything at all.
I moved it to home and it built and ran without any issues what so ever.

By tied to /tmp I meant to say,that project **will** only be created if ```dest_dir``` is located in /tmp.

Later moving whole work directory from /tmp does not break a single damn thing.

Kudos and thanks for this beautiful app!

**Comment by aggalex** [comment]
Sorry for not replying on time, I didn't have the time too...
So I tried making Archetype generate an instance, and copying the folder created to my designated place. Archetype seems to be deleting the folder from tmp a while after, so I had to be fast. But I finally made it! Had problems with compiling it though. Ether I don't know how, or there's something missing. Here's the directory tree of my dummy app's folder:
```
.
├── app
├── AUTHORS.md
├── com.generic.rdnn.json
├── data
│   ├── com.generic.rdnn.appdata.xml
│   ├── com.generic.rdnn.desktop
│   ├── com.generic.rdnn.gresource.xml
│   ├── com.generic.rdnn.gschema.xml
│   ├── css
│   │   └── style.css
│   ├── images
│   │   ├── com.generic.rdnn.png
│   │   ├── com.generic.rdnn.svg
│   │   ├── icons
│   │   │   ├── 128
│   │   │   │   └── com.generic.rdnn.svg
│   │   │   ├── 16
│   │   │   │   └── com.generic.rdnn.svg
│   │   │   ├── 24
│   │   │   │   └── com.generic.rdnn.svg
│   │   │   ├── 32
│   │   │   │   └── com.generic.rdnn.svg
│   │   │   ├── 48
│   │   │   │   └── com.generic.rdnn.svg
│   │   │   └── 64
│   │   │       └── com.generic.rdnn.svg
│   │   └── screenshot.png
│   └── meson.build
├── debian
│   ├── changelog
│   ├── compat
│   ├── control
│   ├── copyright
│   ├── rules
│   └── source
│       └── formart
├── LICENSE.md
├── meson
│   └── post_install.py
├── meson.build
├── po
│   ├── com.generic.rdnn.pot
│   ├── LINGUAS
│   ├── meson.build
│   └── POTFILES
├── README.md
├── src
│   ├── Application.vala
│   ├── configs
│   │   ├── Constants.vala
│   │   └── Settings.vala
│   ├── controllers
│   │   └── AppController.vala
│   ├── Main.vala
│   ├── meson.build
│   ├── views
│   │   └── AppView.vala
│   ├── widgets
│   │   └── HeaderBar.vala
│   └── Window.vala
└── tests
    ├── assert.vala
    ├── meson.build
    └── test.vala
```

**Comment by kjlaw89** [comment]
@pavlepiramida So it sounds like it has some issue with moving to a directory outside of /tmp, but once it's created you can take it anywhere and it will work fine.

@aggalex I realized that when I started to look at the code last night. If it succeeds or fails it will attempt to clean up the /tmp directory of any folders created. I'll adjust that in my (attempted) fix. As for building the app, you should be able to open the terminal to your app's folder and run:

`./app install-deps && ./app install && ./app test-run`

`install-deps` will install any missing dependencies, while `install` will install the resources and `test-run` will build, test and run the application.

After you have run `install-deps` and `install`, you can just run `test-run` going forward. If you add any additional resources or change icons you'll need to re-run `install` but until then `test-run` is enough.

**Comment by kjlaw89** [comment]
@pavlepiramida, @aggalex Version 1.0.2 is out now. See if that helps!

**Comment by aggalex** [comment]
I will do that when I finish my economics exams. Thanks!

**Comment by pavlepiramida** [comment]
Works like a charm now!

**Comment by aggalex** [comment]
It indeed works perfectly now. Perhaps You'd like to close the issue.

**Comment by kjlaw89** [comment]
Great! Closing this out as resolved!
